In [5]:
# SVM Classification
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt


In [6]:
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pd.read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

In [7]:
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [3]:
#divide in traing & testing
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [8]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((537, 8), (537,), (231, 8), (231,))

In [9]:
clf=SVC(kernel="rbf",gamma=0.0001)   #create algo  gamma=beta if gamma high then project it to high dimension
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
acc=accuracy_score(y_test,y_pred)*100
print("accuracy=",acc)
confusion_matrix(y_test,y_pred)

accuracy= 73.16017316017316


array([[128,  20],
       [ 42,  41]], dtype=int64)

In [10]:
clf=SVC(kernel="linear",gamma=0.0001)   #create algo  gamma=beta if gamma high then project it to high dimension
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
acc=accuracy_score(y_test,y_pred)*100
print("accuracy=",acc)
confusion_matrix(y_test,y_pred)

accuracy= 74.02597402597402


array([[127,  21],
       [ 39,  44]], dtype=int64)

### Grid Search CV

In [12]:
#find best gamma and best  . c is constant determines contribution of 2nd quantity.if c=0 contri is 0.it is better as hard classifier
#if c is high we give high penalty if it lies on wrong side & viceversa
#gamma is for dimension 
#kernel=rbf finds best set of gamma and c
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [13]:
gsv.best_params_ , gsv.best_score_  #gives best value

({'C': 15, 'gamma': 50, 'kernel': 'rbf'}, 0.6555206149545771)

In [14]:
clf = SVC(C= 15, gamma = 50)
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 64.06926406926407


array([[148,   0],
       [ 83,   0]], dtype=int64)